FROM registry.redhat.io/openshift4/ose-cli:latest as ose-cli

FROM registry.access.redhat.com/ubi9:9.2-722

ARG CREATED_AT=none
ARG GITHUB_SHA=none

LABEL org.opencontainers.image.created="$CREATED_AT"
LABEL org.opencontainers.image.revision="$GITHUB_SHA"

LABEL org.opencontainers.image.title="Terminal"
LABEL org.opencontainers.image.description="Web terminal access from the browser."
LABEL org.opencontainers.image.url="https://github.com/juliaaano/showroom"
LABEL org.opencontainers.image.source="git@github.com:juliaaano/showroom"
LABEL org.opencontainers.image.documentation="https://github.com/juliaaano/showroom"
LABEL org.opencontainers.image.authors="juliaaano"
LABEL org.opencontainers.image.vendor="juliaaano"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.version="1.0.0"

RUN curl -L https://github.com/tsl0922/ttyd/releases/download/1.7.3/ttyd.x86_64 --output /tmp/ttyd.x86_64 && \
    chmod +x /tmp/ttyd.x86_64 && \
    mv /tmp/ttyd.x86_64 /usr/bin/ttyd

COPY --from=ose-cli /usr/bin/kubectl /usr/bin/
COPY --from=ose-cli /usr/bin/oc /usr/bin/

USER 1001

CMD ["ttyd", "-p 8080", "bash"]
