= SHOWROOM

Welcome to the showroom OpenShift application.

== Install

A basic installation will vary depending if you have a docs site running or you want to build and serve
the documentation from the source code.

=== Namespace creation

. Deploying as cluster-admin (default)

By default, this Helm Chart attempts to create a Namespace for showroom.
As cluster-admin can create and manage cluster resources like Namespaces

. Deploying as Service Account

If you will be deploying this Helm Chart as a service account, you must create the Namespace in advance.
Indicate `--set namespace.create=false` in your execution of this command to avoid RBAC errors.

=== Namespace name generation

Typically, user interface namespace names have been just `bookbag-GUID` or `showroom-GUID`.
This makes management and cleanup a bit difficult.

=== Deploy Showroom - Parameters


In this scenario you have:

* a Git repo URL with an Antora website and want OpenShift to build and deploy
* login as an OpenShift user that can create cluster resources (namespaces, etc) like cluster-admin
* FQDN of your default OpenShift route.
Example: apps.shared-410.openshift.redhatworkshops.io
* Namespace
** A Namespace name like `showroom-test`: `namespace.name=test`
+
or
+
** <namespace>-<guid> composed of `general.namespace=showroom` and `general.guid=test`.
Defaults to `showroom-test`

.Deploy as cluster-admin with `helm template` *RECOMMENDED*
```
git clone https://github.com/rhpds/showroom-deployer
cd ./showroom-deployer/charts

helm template ./showroom \
--set deployer.domain=apps.shared-410.openshift.redhatworkshops.io \
--set general.guid=GUID \
--set-file content.user_data=<path-to-user-data.yaml> \
--set documentation.repoUrl=https://github.com/rhpds/showroom_template_default \
| oc apply -f -
```

.Deploy as cluster-admin with `helm install`
```
 helm repo add rhpds https://rhpds.github.io/showroom-deployer
```
. Refresh them

 helm repo update

. Install the latest
```
 helm install myshowroom rhpds/showroom
--create-namespace \
--set deployer.domain=apps.shared-410.openshift.redhatworkshops.io \
--set general.guid=GUID \
--set-file content.user_data=<path-to-user-data.yaml> \
--set documentation.repoUrl=https://github.com/rhpds/showroom_template_default

helm install myshowroom myrhpds/showroom --set deployer.domain=apps.shared-410.openshift.redhatworkshops.io --set general.guid=test --set-file content.user_data=/Users/jmaltin/tmp/azure-user-data.yaml --debug --create-namespace --set namespace.create=false
```

NOTE: The above creates the namespace `showroom-test` where the helm release exists, AND creates the namespace `showroom-test2` there the actual application is deployed.

== ArgoCD - *Work in Progress* - BROKEN

It is possible to deploy the helm chart with ArgoCD.
This repo provides an ArgoCD/Application for your convenience.

```
oc create -f ./setup/argocd/application.yaml
```

== Multi-user installation - *Work in Progress* - BROKEN

The chart can be installed multiple times in one namespace per user. You control this in helm values.yaml.

An easy way to setup and manage a multi-user deployment is via the ArgoCD/ApplicationSet.

```
oc create -f ./argocd/applicationset.yaml
```

== Use \https://rhpds.github.io/ in your git repo as Helm Repo

=== Prereqs

I added a few actions to the rhpds github org.

* helm/chart-releaser-action@v1.5.0
* helm/chart-testing-action@master

=== Setup

. Setup a branch in your repo which gh-pages will host.
Call it `gh-pages`
+
----
git checkout --orphan gh-pages
git rm -rf .
git commit -m "Initial commit for gh-pages" --allow-empty
git push
----
. Get gh-pages working for your repo.
.. Go to the `settings` page on your repository and set the `source branch` to the `gh-pages` branch you just created.
. Check out the github workflows in this repo for
.. link:.github/workflows/ci.yaml[.github/workflows/ci.yaml]: PRs to `/charts` automatically Lint and Test Charts
... [NOTE] Should be upgraded per: https://github.com/marketplace/actions/helm-chart-testing
.. link:.github/workflows/release-helm.yaml[.github/workflows/release-helm.yaml]: Commits to `/charts` triggering a release to \https://rhpds.github.io/<your repo name>

=== Testing your new Chart Repo

Just like you'd use any Helm repo

. Add the repo

 helm repo add myrhpds https://rhpds.github.io/showroom-deployer

. Refresh them

 helm repo update

. Install the latest

 helm install showroom <lots of parameters>

== TODO

. Basic AgD Integration
. Test applicationSet
. for dedicated OCP cluster, just install helm chart (?)
. ssh to bastion automatically if set
