FROM registry.access.redhat.com/ubi9:9.2-722

ARG CREATED_AT=none
ARG GITHUB_SHA=none

LABEL org.opencontainers.image.created="$CREATED_AT"
LABEL org.opencontainers.image.revision="$GITHUB_SHA"

LABEL org.opencontainers.image.title="Showroom Terminal"
LABEL org.opencontainers.image.description="Web terminal access from the browser."
LABEL org.opencontainers.image.url="https://github.com/rhpds/showroom-deployer"
LABEL org.opencontainers.image.source="git@github.com:rhpds/showroom-deployer"
LABEL org.opencontainers.image.documentation="https://github.com/rhpds/showroom-deployer"
LABEL org.opencontainers.image.authors="rhpds"
LABEL org.opencontainers.image.vendor="rhpds"
LABEL org.opencontainers.image.licenses="GPL3+"
LABEL org.opencontainers.image.version="1.0.0"

RUN curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz \
  --output openshift-client-linux.tar.gz && \
  tar xzf openshift-client-linux.tar.gz && \
  install -t /usr/bin oc kubectl

RUN curl -L https://github.com/tsl0922/ttyd/releases/download/1.7.3/ttyd.x86_64 --output /tmp/ttyd.x86_64 && \
    chmod +x /tmp/ttyd.x86_64 && \
    mv /tmp/ttyd.x86_64 /usr/bin/ttyd

RUN dnf --quiet -y install unzip ncurses git

RUN rpm --quiet -ih http://galaxy4.net/repo/RHEL/9/x86_64/tmux-3.3a-1.el9.x86_64.rpm

RUN curl -s -L "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
    -o "awscliv2.zip" && \
    unzip -u awscliv2.zip && \
    ./aws/install

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh


RUN useradd -u 1001 -ms /bin/bash lab-user && \
    mkdir -p /lab-user && \
    chown -R lab-user:lab-user /home/lab-user

#RUN echo 'if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then exec tmux; fi' \
#    >> /home/lab-user/.bashrc && \
#    chown lab-user:lab-user /home/lab-user/.bashrc

USER 1001

CMD ["ttyd", "-p 8080", "tmux"]
