== Overview

This container takes Antora-based content git repos, does attribute injection, generates HTML and launches a trivial web server to host it.

===

Prereqs:
* git repo in Antora format with Asciidoc of your content
** Example: https://github.com/rhpds/showroom_template_default
** /site.yml is the default Antora Playbook, set env var ANTORA_PLAYBOOK to override
** /content/antora.yml for your component.
* Volumes:
** Git clone: /showroom/repo
** Antora HTML output: /showroom/www
** User Data
*** OpenShift: ConfigMap (preferably) of AgnosticD user_data as volume mounted on /user_data/user_data.yml with agnosticD user_data
*** Podman/Docker: Empty Volume on /showroom/ for /showroom/repo and /showroom/www

Asciidoc attributes:
* This container will merge YAML in /user_data/user_data.yml and /content/antora.yml to provide asciidoc attributes to your Antora component
* TODO: create mechanism to support multiple components

=== Quickstart Container Runtime

Build the container:

 podman build -t showroom-allinone .

Prepare local directories and files

 mkdir repo user_data

Put user data into place.
Here I just create dummy data, because I don't have a file:

 echo "attribute_name: attribute_value" > user_data/user_data.yml

Run the container:

 podman run -d -e GIT_REPO_URL=https://github.com/rhpds/aro-ilt -e USER_DATA_FILE=user-data.yaml -v $PWD/showroom/:/showroom/ -v $PWD/user_data/:/user_data/ -p8000:8000 -it showroom-allinone

NOTE:  You can change the ANTORA_PLAYBOOK by setting that environemnt variable to the filename of the antora playbook in the git repo

Access the website:

http://localhost:8000

== TODO

* DONE: setup httpd
* DONE: allow multiple runs of `git clone` against /showroom/repo/

== Change Log

====
* Date: 2023-10-12 Author: jmaltin

*Major entrypoint.sh update*

    * env var ANTORA_PLAYBOOK accepted, defaults to site.yml
    * combine all volumes into one /showroom
    * update README with mounting instructions for /showroom
    * clone repo into /showroom/repo
    * pick up user_data from /user_data/user_data.yml
    * run yp with in-place on /showroom/repo/content/antora.yml to merge in
      /user_data/user_data.yml
    * antora generate: output forced to /showroom/www/
    * use python built in http server on port 8000
    * make USER_DATA_FILE configurable in the environment
====
