{{- if eq .Values.ocpconsole.setup "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: console-{{ .Values.ocpconsole.user }}
  namespace: {{ .Values.ocpconsole.user }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: console-{{ .Values.ocpconsole.user }}
  namespace: showroom-{{ .Values.ocpconsole.user }}
{{- end }}
