{{- if eq .Values.ocpconsole.setup "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: console-secret
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/service-account.name: console-{{ .Values.ocpconsole.user }}
type: kubernetes.io/service-account-token
{{- end }}
