{{- if eq .Values.ocpconsole.setup "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "console-{{ .Values.ocpconsole.user }}"
  namespace: "{{ .Release.Name }}-{{ .Values.ocpconsole.user }}"
{{- end }}
