# Use Red Hat UBI9 as the base image
FROM registry.redhat.io/openshift4/ose-cli:latest as ose-cli

FROM registry.access.redhat.com/ubi9:9.2-722

# Install necessary tools
RUN dnf install -y \
    git

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh

COPY --from=ose-cli /usr/bin/kubectl /usr/bin/
COPY --from=ose-cli /usr/bin/oc /usr/bin/

# Create a user named 'helm'
# RUN useradd -ms /bin/bash helm
RUN useradd -u 1001 -ms /bin/bash helm && \
    mkdir -p /helm && \
    chown -R helm:helm /helm

# Copy the entrypoint script into the container
COPY entrypoint.sh /entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x /entrypoint.sh

# Change ownership of the entrypoint script to the antora user
RUN chown helm:helm /entrypoint.sh

# Switch to the 'helm' user
USER helm

# Set the entrypoint script as the command to run when the container starts
ENTRYPOINT ["/entrypoint.sh"]
