---
apiVersion: v1
kind: Service
metadata:
  name: windows-tokengen
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
