---
apiVersion: v1
kind: Service
metadata:
  name: windows-ironrdp
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
