---
# Source: showroom-single-pod/templates/terminal/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name
  namespace: default
---
# Source: showroom-single-pod/templates/proxy/configmap-index.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-index
  namespace: default
data:
  index.html: |

    <!DOCTYPE html>
    <html>
      <head>
        <title>Showroom</title>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" type="text/css" href="split.css">
        <link rel="stylesheet" type="text/css" href="tabs.css">
      </head>
      <body>
        <div class="content">
          <div class="split left">
            <iframe id="doc" src="https://release-name-default.cluster-GUID.GUID.sandboxNUMBERS.opentlc.com/content" width="100%" style="border:none;"></iframe>
          </div>
          <div class="split right">
            <div class="tab">
    
    <!-- primary tabbed terminals - start -->
                <button class="tablinks" onclick="openTerminal(event, 'terminal_tab1')" id="defaultOpen" tabindex="0">Terminal 1</button>
                <button class="tablinks" onclick="openTerminal(event, 'wetty_tab1')" id="defaultOpen" tabindex="0">Login Terminal 1</button>
    <!-- primary tabbed terminals - end -->
    
    <!-- second tabbed terminals - start -->
                  <button class="tablinks" onclick="openTerminal(event, 'terminal_tab2')" id="defaultOpen" tabindex="0">Terminal 2</button>
                  <button class="tablinks" onclick="openTerminal(event, 'wetty_tab2')" id="defaultOpen" tabindex="0">Terminal 2</button>
    <!-- second tabbed terminals - end -->
    
    <!-- stacked terminals - start -->
    <!-- stacked terminals - end -->
    
    <!-- other tabs - start -->
    <!-- other tabs - end -->
            </div>
    
    <!-- iframe definition - start -->
    <!-- primary tabbed terminals iframes - start -->
              <div id="terminal_tab1" class="tabcontent">
                <iframe id="terminal_01" src="https://release-name-default.cluster-GUID.GUID.sandboxNUMBERS.opentlc.com/terminal" width="100%" style="border:none;"></iframe>
              </div>
              <div id="wetty_tab1" class="tabcontent">
                <iframe id="terminal_01" src="https://release-name-default.cluster-GUID.GUID.sandboxNUMBERS.opentlc.com/tty1" width="100%" style="border:none;"></iframe>
              </div>
    <!-- primary tabbed terminals iframes - end -->
    
    <!-- second tabbed terminals iframes - start -->
              <div id="terminal_tab2" class="tabcontent">
                <iframe id="terminal_02" src="https://release-name-default.cluster-GUID.GUID.sandboxNUMBERS.opentlc.com/terminal" width="100%" style="border:none;"></iframe>
              </div>
              <div id="wetty_tab2" class="tabcontent">
                <iframe id="terminal_02" src="https://release-name-default.cluster-GUID.GUID.sandboxNUMBERS.opentlc.com/tty1" width="100%" style="border:none;"></iframe>
              </div>
    <!-- second tabbed terminals iframes - end -->
    
    <!-- stacked terminals iframes - start -->
    <!-- stacked terminals iframes - end -->
    
    <!-- other iframes - start -->
    <!-- other iframes - end -->
    
          </div>
        </div>
    <!-- iframe definition - end -->
        <script>
          document.getElementById("defaultOpen").click();
          function openTerminal(evt, tabName) {
            // Declare all variables
            var i, tabcontent, tablinks;
            // Get all elements with class="tabcontent" and hide them
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) {
              tabcontent[i].style.display = "none";
            }
            // Get all elements with class="tablinks" and remove the class "active"
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
              tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            // Show the current tab, and add an "active" class to the button that opened the tab
            document.getElementById(tabName).style.display = "block";
            evt.currentTarget.className += "active";
          }
        </script>
        <script src="https://unpkg.com/split.js/dist/split.min.js"></script>
        <script>
          Split(['.left', '.right'], {
            sizes: [45,55],
          });
          Split(['.top', '.bottom'], {
            sizes: [65,35],
            direction: 'vertical',
          });
        </script>
      </body>
    </html>
    
  split.css: |

    * {
      box-sizing: border-box;
      height:100%;
    }
    
    body {
      margin: 0;
      height:100%;
      /* font-size: 26px;*/
    }
    
    .content {
      width: 100%;
      height: 100%;
      padding: 0px;
      display: flex;
      justify-items: center;
      align-items: center;
      border-top: 1px solid;
      border-color: Gainsboro;
      border-top-width: thin;
      margin-top: 0px;
    }
    
    .split {
      width:100%;
      height:100%;
      padding: 5px;
    }
    
    .left {
      height: 100%
    }
    
    .right {
      height: 100%
    }
    
    .gutter {
      /* cursor: e-resize; */
      /* background: grey; */
      height: 98%;
      background-color: #eee;
      background-repeat: no-repeat;
      background-position: 50%;
    }
    
    .gutter.gutter-horizontal {
      background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAeCAYAAADkftS9AAAAIklEQVQoU2M4c+bMfxAGAgYYmwGrIIiDjrELjpo5aiZeMwF+yNnOs5KSvgAAAABJRU5ErkJggg==');
      cursor: col-resize;
    }
    .gutter.gutter-vertical {
      background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAFAQMAAABo7865AAAABlBMVEVHcEzMzMzyAv2sAAAAAXRSTlMAQObYZgAAABBJREFUeF5jOAMEEAIEEFwAn3kMwcB6I2AAAAAASUVORK5CYII=');
      cursor: row-resize;
    }
    
    
  tabs.css: |

    /* Style the tab */
    
    .tab {
      overflow: hidden;
      border: 1px solid #ccc;
      background-color: #f1f1f1;
      height: 50px;
    }
    
    /* Style the buttons that are used to open the tab content */
    
    .tab button {
      background-color: inherit;
      float: left;
      border: none;
      outline: none;
      cursor: pointer;
      padding: 14px 16px;
      transition: 0.3s;
    }
    
    /* Change background color of buttons on hover */
    
    .tab button:hover {
      background-color: #ddd;
    }
    
    /* Create an active/current tablink class */
    
    .tab button.active {
      background-color: #ccc;
    }
    
    /* Style the tab content */
    
    .tabcontent {
      display: none;
      padding: 6px 12px;
      border: 1px solid #ccc;
      border-top: none;
      /* 100% - height of the tab above */
      height: calc(100% - 50px);
    }
---
# Source: showroom-single-pod/templates/proxy/configmap-nginx-config.yaml
kind: ConfigMap
metadata:
  name: release-name-proxy-config
  namespace: default
apiVersion: v1
data:
  nginx.conf: |
    #daemon off;
    events {
    }
    error_log /dev/stdout info;
    http {
      include /etc/nginx/mime.types;
      proxy_cache off;
      expires -1;
      proxy_cache_path /dev/null keys_zone=mycache:10m;

      map $http_upgrade $connection_upgrade {
          default upgrade;
          '' close;
      }

      server {
        listen 8080;

        absolute_redirect off;

        location / {
          proxy_pass http://localhost:8000;
          rewrite ^/(.*)$ /$1 break;

          expires off;
          proxy_cache off;
          proxy_pass_request_headers on;
          proxy_set_header Accept-Encoding "gzip";
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /content/ {
          proxy_pass http://localhost:8000;
          rewrite ^/content/(.*)$ /$1 break;

          expires off;
          proxy_cache off;
          proxy_pass_request_headers on;
          proxy_set_header Accept-Encoding "gzip";
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /terminal/ {
          proxy_pass http://localhost:7681;
          rewrite ^/terminal/(.*)$ /$1 break;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 43200000;

          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
        }
        location ^~ /tty1 {
          proxy_pass http://localhost:8001/wetty;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 43200000;

          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
        }
        location ^~ /wetty {
          proxy_pass http://localhost:8001/wetty;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 43200000;

          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
        }
        location ^~ /runner {
          rewrite ^/runner(/.*)$ $1 break;
          proxy_pass http://localhost:8501/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 43200000;
    
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
        }
      }
    }
---
# Source: showroom-single-pod/templates/proxy/configmap-user-data.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-userdata
  namespace: default
data:
  user_data.yml: |
    bastion_password: from_helm
---
# Source: showroom-single-pod/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-name-terminal-lab-user-home
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: showroom-single-pod/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-name-files
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
# Source: showroom-single-pod/templates/terminal/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-release-name-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: release-name
  namespace: default
---
# Source: showroom-single-pod/templates/proxy/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: release-name
---
# Source: showroom-single-pod/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: release-name
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: release-name
    spec:
      serviceAccountName: release-name
      initContainers:
      - name: git-cloner
        image: quay.io/andrew-jones/git-cloner:v0.0.1
        env:
        - name: GIT_REPO_URL
          value: https://github.com/agonzalezrh/zt-get-started-ansible-navigator.git
        - name: GIT_REPO_REF
          value: main
        volumeMounts:
        - mountPath: /files
          name: release-name-files
      - name: antora-builder
        image: docker.io/antora/antora:3.1.10
        command: ['sh', '-c', "until [ -f .init.completed ]; do echo waiting for files; sleep 1; done; antora --stacktrace site.yml"]        
        volumeMounts:
        - mountPath: /antora
          name: release-name-files
      # - resources: {}
      #   terminationMessagePath: /dev/termination-log
      #   name: setup
      #   env:
      #     - name: GIT_REPO_URL
      #       value: https://github.com/agonzalezrh/zt-get-started-ansible-navigator.git
      #     - name: GIT_REPO_REF
      #       value: main
      #     - name: BASTION_HOST
      #       value: bastion.krkvq.sandbox114.opentlc.com
      #     - name: BASTION_PORT
      #       value: "22"
      #     - name: BASTION_USER
      #       value: lab-user
      #     - name: BASTION_PASSWORD
      #       value: sVy12ATIDIk9
      #   imagePullPolicy: Always
      #   volumeMounts:
      #     - name: runner
      #       mountPath: /runner/
      #   terminationMessagePolicy: File
      #   image: 'quay.io/agonzalezrh/showroom:setup-v0.1'
      containers:
      - resources: {}
        terminationMessagePath: /dev/termination-log
        name: runner
        env:
          - name: GIT_REPO_URL
            value: https://github.com/agonzalezrh/zt-get-started-ansible-navigator.git
          - name: GIT_REPO_REF
            value: main
          - name: BASTION_HOST
            value: bastion.krkvq.sandbox114.opentlc.com
          - name: BASTION_PORT
            value: "22"
          - name: BASTION_USER
            value: lab-user
          - name: BASTION_PASSWORD
            value: sVy12ATIDIk9
        ports:
          - name: runner
            containerPort: 8501
            protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
          - name: runner
            mountPath: /runner/
        terminationMessagePolicy: File
        image: 'quay.io/agonzalezrh/showroom:runner-v1.13'
      - name: nginx
        image: quay.io/rhpds/nginx:1.25
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        - mountPath: /data/www
          name: content
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /var/run
          name: nginx-pid
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: web
          containerPort: 8080

      - name: content
        image: ghcr.io/rhpds/showroom-content:prod
        imagePullPolicy: IfNotPresent
        env:
        - name: GIT_REPO_URL
          value: https://github.com/agonzalezrh/zt-get-started-ansible-navigator.git
        - name: GIT_REPO_REF
          value: main
        - name: ANTORA_PLAYBOOK
          value: site.yml
        - name: ZT_BUNDLE
          value: https://github.com/rhpds/nookbag/releases/download/nookbag-v0.0.4/nookbag-v0.0.4.zip
        - name: ZT_UI_ENABLED
          value: ""
        volumeMounts:
        - name: user-data
          mountPath: /user_data/
        - name: showroom
          mountPath: /showroom/
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
      - name: terminal
        image: quay.io/rhpds/openshift-showroom-terminal-ocp:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GUID
          value: "nnnnn"
        volumeMounts:
        - name: terminal-lab-user-home
          mountPath: /home/lab-user
        ports:
        - containerPort: 7681
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      - name: wetty
        image: quay.io/rhpds/wetty:latest
        imagePullPolicy: IfNotPresent
        args:
        - --base="/wetty/"
        - --port=8001
        - --ssh-host=bastion.krkvq.sandbox114.opentlc.com
        - --ssh-port=22
        - --ssh-user=lab-user
        - --ssh-auth=password
        - --ssh-pass=sVy12ATIDIk9
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GUID
          value: "nnnnn"
        ports:
        - containerPort: 8001
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi

      volumes:
      - name: runner
        emptyDir: {}
      - name: showroom
        emptyDir: {}
      - name: user-data
        configMap:
          name: release-name-userdata
      - name: content
        configMap:
          name: release-name-index
      - name: nginx-config
        configMap:
          defaultMode: 420
          name: release-name-proxy-config
      - name: nginx-pid
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: terminal-lab-user-home
        persistentVolumeClaim:
          claimName: release-name-terminal-lab-user-home
      - name: release-name-file
        persistentVolumeClaim:
          claimName: release-name-files
---
# Source: showroom-single-pod/templates/proxy/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: release-name
  namespace: default
  annotations:
    haproxy.router.openshift.io/timeout: 1h
    haproxy.router.openshift.io/timeout-tunnel: 1h
spec:
  to:
    kind: Service
    name: release-name
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
