# Use an official Traefik image as the base image
FROM traefik:v2.5

# Expose ports
EXPOSE 8080
EXPOSE 4430

# Create a non-root user
RUN adduser -D -H -u 1001 -s /sbin/nologin traefik

# Set the user to run Traefik as a non-root user
USER traefik

# Entrypoint command
CMD ["traefik"]

