---
name: publish
on:
  push:
    branches-ignore:
    - '*'
    tags:
    - 'v[0-9]*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Get image tags
      id: image_tags
      run: |
        # Version is a semantic version tag or semantic version with release number
        # GITHUB_REF will be of the form "refs/tags/v0.1.2" or "refs/tags/v0.1.2-1"
        # To determine RELEASE, strip off the leading "refs/tags/"
        RELEASE=${GITHUB_REF#refs/tags/}
        # To determine VERSION, strip off any release number suffix
        VERSION=${RELEASE/-*/}

        # Check version from helm/Chart.yaml
        HELM_CHART_VERSION=$(sed -nr 's/^appVersion: (.*)/\1/p' helm/Chart.yaml)
        if [[ "v${HELM_CHART_VERSION}" != "${VERSION}" ]]; then
          echo "Helm chart version does not match tag!"
          exit 1
        fi

        # Only build image if version tag without release number
        # Releases indicate a change in the repository that should not trigger a new build.
        if [[ "${VERSION}" == "${RELEASE}" ]]; then
          # Publish to latest, minor, and patch tags
          # Ex: latest,v0.1.2,v0.1
          echo "IMAGE_TAGS=latest ${VERSION%.*} ${VERSION}" >> $GITHUB_OUTPUT
        fi

  publish-helm-charts:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Configure Helm
      uses: azure/setup-helm@v1
      with:
        version: latest

    - name: Package Helm Chart
      run: |
        helm dep up helm/
        helm package helm/
        mv showroom-*.tgz gh-pages
        helm repo index --url https://agonzalezrh.github.io/showroom gh-pages

    - name: Push Changes to GH Pages
      run: |
        cd gh-pages
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add .
        git commit -m "Updating Helm Chart Repository"
        git push
